### ISSUE TITLE
Determine the Anniversary website Name.

### ISSUE THREAD

**Issue by boborugged** [lhnyc/anniversary#1]
We really do not need to do this, a the anniversary site could be part of the existing website. However as a learning experience, we can go from start to finish on build a site thus the reason for attempting to pick a separate site name.

Any ideas ?

**Comment by wale1958** [comment]
lh1stanniersary.com is available

**Comment by boborugged** [comment]
How about     `LH1st.us`  ?

**Comment by wale1958** [comment]
Yeah that works as well

**Comment by wale1958** [comment]
Do you mind if I come to your house on Saturday to work on it ？

**Comment by boborugged** [comment]
Yes, you can come over, anytime after 3:45pm

**Comment by boborugged** [comment]
It was finally determined today to use the following domain name : 

> lighthouse1st.us
